(defun bb/spaces-before (n)
  (interactive "p")
  (dotimes (c n nil)
    (insert " ")))

(defun bb/spaces-after (n)
  (interactive "p")
  (forward-char)
  (dotimes (c n nil)
    (insert " "))
  (backward-char (1+ n)))

(defun bb/empty-commit ()
  (interactive)
  (insert ".")
  (call-interactively 'with-editor-finish))
